require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4

Naming/FileName:
  Exclude:
    - engines/algolia-autocomplete-rails/lib/algolia-autocomplete-rails.rb

Layout/LineLength:
  Max: 120

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/production.rb # rails

Lint/MissingSuper:
  Exclude:
    - app/components/**/*.rb

Metrics/AbcSize:
  Exclude:
    - app/components/**/*.rb
    - app/views/**/*.rb

Metrics/BlockLength:
  Exclude:
    - app/components/**/*.rb
    - app/views/**/*.rb

Metrics/MethodLength:
  Exclude:
    - app/components/**/*.rb
    - app/views/**/*.rb

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Exclude:
    - app/controllers/**/*.rb
    - app/helpers/application_helper.rb
    - app/models/application_record.rb
    - app/views/**/*.rb
    - config/application.rb
    - db/migrate/**/*.rb
    - test/**/*.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - config/**/*.rb # rails config files skip this

Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb # rails

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/StringLiterals:
  Exclude:
    - config/**/*.rb # rails files use double quotes

Style/SymbolArray:
  Exclude:
    - config/initializers/filter_parameter_logging.rb # rails
