require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 120

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/production.rb # rails

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Exclude:
    - app/controllers/**/*.rb
    - app/helpers/application_helper.rb
    - app/models/application_record.rb
    - config/application.rb
    - db/migrate/**/*.rb
    - test/**/*.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - config/**/*.rb # rails config files skip this

Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb # rails

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/StringLiterals:
  Exclude:
    - config/**/*.rb # rails files use double quotes

Style/SymbolArray:
  Exclude:
    - config/initializers/filter_parameter_logging.rb # rails