require: rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 120

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Exclude:
    - app/controllers/**/*.rb
    - app/helpers/application_helper.rb
    - app/models/application_record.rb
    - config/application.rb
    - db/migrate/**/*.rb
    - test/**/*.rb

Style/HashSyntax:
  EnforcedShorthandSyntax: either
