name: minitest
on:
  - push

jobs:
  tests:
    name: minitest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bundle install
          bundle exec rails test:prepare
          bundle exec rails test
